### ISSUE TITLE
Загружается 2 файла вместо одного

### ISSUE THREAD

**Issue by cmsworksru** [esclkm/mavatars#11]
При включении Ajax и загрузке одной картинки, она дублируется, то есть загружается два раза. (Посмотри на демо фриланс-биржи)

**Comment by applesin** [comment]
Костыльное решение "plugins/mavatars/inc/mavatars.functions.php".
 	function upload($input_name = 'mavatar_file')
 	{
 
-		global $db, $db_mavatars;
+		global $cfg, $db, $db_mavatars;
+        if ($cfg['turnajax']) {
+            return false;
+        }
 		$order = count($this->mavatars);
 		$files_array = array();
 		if (is_array($_FILES[$input_name]['name']))

**Comment by devkont** [comment]
Не совсем конечно правильно, но мысль верная. Спасибо! Поправим в сборке биржи))
